### ISSUE TITLE
Renaming read tags

### ISSUE THREAD

**Issue by winni2k** [timoast/sinto#12]
I need to temporarily remove read groups from my BAM file in order to run BQSR in a read-group unaware mode. I thought I might just rename the RG read tag to something else while I run BQSR and then rename the read tag back to RG. I've looked around a little, and I can't find a tool to do it, so I'm writing a script for it. Would that be something you would accept a PR for?

**Comment by timoast** [comment]
Sure, I think having functions to move information around in a bam file would be useful (read group to read tag, read name to read tag, read tag to read group, etc.).

**Comment by winni2k** [comment]
Excellent. I'll post a PR when I have something written.
