### ISSUE TITLE
filterbarcodes bam outputs very small?

### ISSUE THREAD

**Issue by Annika18** [timoast/sinto#16]
Hi, I'm new to using this tool and not sure if it worked correctly.

I have a sorted BAM file of attack seq data that's ~100 Gb, and 12 clusters that I'm looking to subset the data into. The filterbarcodes function ran with no errors, but I am having trouble understanding the output. The 12 bam files all were tiny in comparison to the original BAM file (each about 2 kilobytes), where I thought they would each roughly be 1/12 the size of the original BAM file. 

Also, each bam file (ex. 0.bam) seems to be accompanied by another binary file named something like 0_7U58WO (also around 2 kb), that I can't figure out how to read or what it is.

I'm not sure how to make sense of this because there were no errors indicated while running the program. Anything that could shed light on these unexpected results would be helpful.

**Comment by timoast** [comment]
Hi, are you sure there was no error? It sounds like the merge step might have failed (merging the temporary bam files generated by each process). However, if the temp files are also 2 kb then they're all empty. Is it possible that the barcodes you requested were not present in the BAM file? You could do a manual check for one barcode you expect to be in the file using `samtools view [bamfile] | grep [barcode] | head`

**Comment by Annika18** [comment]
Hi, thank you for your response. You were right, I figured out yesterday that my barcode_regex was wrong (I should have just been using the default), and re-ran the command.

I still have a clarification question-- this most recent run, the size of all my BAM files added together was around 10Gb, only around 1/10 the size of the source BAM file. Is there a reason that the output would be so much smaller (All cells were assigned to a group in my cell file, I wasn't intentionally removing any), or should I be concerned that these clustered BAM files are possibly missing data?

**Comment by timoast** [comment]
The size of the files will depend on what percentage of the reads in the BAM file correspond to a cell. If you had a large number of reads in your experiment that originate from barcodes not linked to a cell, then it's possible that the total size of the split files will be lower than the size of the original file.
