### ISSUE TITLE
Memory issue with Add cell barcodes to FASTQ read names function

### ISSUE THREAD

**Issue by baigal628** [timoast/sinto#23]
Hi, 

I am trying to use sinto barcode command to add the cell barcodes stored in R2.fastq to the R1 and R3 scATAC-seq reads. Here is the command I am using. The command gives the right output but the only problem is that it is using ~30G RAM per sample, which means I will have to assign a lot of memory if running parallel. It would be helpful if you could provide any potential solutions for that. Thanks!

$ sinto barcode --barcode_fastq R2.fastq --read1 R1.fastq --read2 R3.fastq -b 16

The size of certain sample files:
13G	R1.barcoded.fastq
20G	R3.barcoded.fastq
15G	R1.fastq
7.4G	R2.fastq
15G	R3.fastq

**Comment by timoast** [comment]
Sinto first reads all the cell names and puts them into a list, which is probably why this uses so much memory. You could try using [volans](https://github.com/parazodiac/Volans) instead, which is a more efficient implementation that streams through all three files.

**Comment by baigal628** [comment]
Thanks for your suggestion. I will look into that.

**Comment by ghuls** [comment]
@baigal628 
You can also take a look at:
https://github.com/aertslab/single_cell_toolkit/blob/master/debarcode_10x_scatac_fastqs.sh

It requires `mawk` (https://invisible-island.net/mawk/) for rewriting FASTQ files and `bgzip` (in htslib: https://www.htslib.org/download/) for compressing them (instead of gzip) in parallel.

It is much faster than `sinto barcode` and processes the FASTQ files by streaming:

```bash
./debarcode_10x_scatac_fastqs.sh

Usage:   debarcode_10x_scatac_fastqs fastq_R1 fastq_R2 fastq_R3 fastq_output_prefix [barcode_read_name_separator]

Purpose: Debarcode 10x scATAC FASTQ files by adding the cell barcode from R2
         in front of the original read name for each read in R1 and R3
         (separated by barcode_read_name_separator (default: "-")).


# Add cell barcodes to FASTQ read names
./debarcode_10x_scatac_fastqs.sh R1.fastq.gz R2.fastq.gz R3.fastq.gz barcoded"-"


# This will create 2 FASTQ files:
barcoded_R1.fastq.gz ==> R1 reads with R2 barcode added to readname
barcoded_R2.fastq.gz ==> R3 reads with R2 barcode added to readname
```
