### ISSUE TITLE
filterbarcodes - Samtools merge failed

### ISSUE THREAD

**Issue by rb56** [timoast/sinto#27]
Hi , I'm trying to run Sinto filterbarcodes -b <bam-file>.bam -p 1 -c <metadata>.csv and I get this error:

[E::hts_open_format] Failed to open file "8.tmp > 8.bam" : No such file or directory
samtools reheader: fail to open file '8.tmp > 8.bam': No such file or directory

File "/ihome/rlafyatis/rib35/.local/lib/python3.7/site-packages/sinto/filterbarcodes.py", line 58, in mergeAll
    raise Exception("samtools merge failed, temp files not deleted")
Exception: samtools merge failed, temp files not deleted

I'm not sure why I'm getting this error and would appreciate any help.

Thank you!

**Comment by timoast** [comment]
Hi @rb56 , sorry for the delay. Can you confirm that there are cell barcodes in the bam file that belong to group 8 in the csv file?

**Comment by macros29** [comment]
Duplicate of #41 Turns out you need Samtools on PATH for it to work.
