### ISSUE TITLE
sinto filterbarcodes error - OSError: truncated file

### ISSUE THREAD

**Issue by onionpork** [timoast/sinto#38]
Hey there, 

I am running sintp filterbarcodes to splitbam file. 
Cmd: sinto filterbarcodes -b $.bam -c $cells -p 16
The error message shown as below:

[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File ".../lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File ".../lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File ".../lib/python3.9/site-packages/sinto/filterbarcodes.py", line 21, in _iterate_reads
    for r in inputBam.fetch(i[0], i[1], i[2]):
  File "pysam/libcalignmentfile.pyx", line 2086, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file
"""

Thank you very much for the help!
Bests,

**Comment by timoast** [comment]
Is it possible the bam file is truncated?

**Comment by onionpork** [comment]
Thank you very much for the quick reply.
I checked the bam file by " samtools quickcheck", it seems ok.
Do you have any other suggestion to check whether the the bam file is truncated or not?

The bam file and corresponding bai file I used is from 10XGenomics 
https://www.10xgenomics.com/resources/datasets/pbmc-from-a-healthy-donor-granulocytes-removed-through-cell-sorting-10-k-1-standard-2-0-0

I am trying to split _atac_.bam
Thank you very much.

**Comment by onionpork** [comment]
Yes, you are right. The problem is solved after I re-downloaded the bam file. 
Thank you so much for the help!
