### ISSUE TITLE
Filter cell barcodes from BAM file using read tag other than "CB"

### ISSUE THREAD

**Issue by liaojinyue** [timoast/sinto#4]
Hi timoast,

Thank you for this very nice tool. Is it possible to add an option in "filterbarcodes" function that allow using different read tag? I've data from BioRad platform and the tag is "DB".

Best,

Jason

**Comment by timoast** [comment]
Added `barcodetag` and `barcode_regex` parameters to `filterbarcodes` in v0.3.2. You can set the read tag used for the cell barcode using `--barcodetag DB`
