### ISSUE TITLE
Samtools is not a dependency 

### ISSUE THREAD

**Issue by macros29** [timoast/sinto#41]
Hi @timoast,

I installed sinto with conda (```conda install sinto```) in a new env. It looks like samtools was not one of the dependencies and was not installed automatically, so I have to manually install it to make it work. Would you consider mentioning it in your installation guide or make samtools a dependency?

**Comment by timoast** [comment]
Right, we depend on pysam rather than samtools. Is there a sinto function that you find doesn't work without samtools installed?

**Comment by macros29** [comment]
Yes. When I run ```sinto filterbarcodes``` without samtools, it generates an internal error ```no samtools found``` and the program terminates because no .tmp file was created.

**Comment by timoast** [comment]
You’re right, I forgot that we call samtools directly in that function. I’ll see if there’s a way to do it via pysam, and if not we can add samtools as a dependency

**Comment by hukai916** [comment]
Hi Tim,

The `addtags` also relies on samtools. There may be more functions that require samtools. So, might be easier to simply add samtools as dependency.

Kai

**Comment by timoast** [comment]
This should be fixed now on the develop branch
