### ISSUE TITLE
error reading barcodes file with `read_cell_barcode_file`

### ISSUE THREAD

**Issue by LiNk-NY** [timoast/sinto#44]
Hi Tim, @timoast

Thank you for working on this useful tool. 
I'm trying to make sure that my barcode file is formatted properly and is able to be read in. 
Is it necessary to have a groups column in the cells file? 
I am currently using a text file with only one barcode per line. 

```sh
mramos@super ~/data/10x/pbmc_3k $ cat test_atac_barcodes.txt | head -3
TTAGTCAGTCCTCCCA-1
CATATAGAGTCAAGAC-1
GATATGATCTAATCCG-1
```

I get a "list index out of range" error. 

```py
sinto_dir = os.path.expanduser("~/gh/sinto/sinto")
os.chdir(sinto_dir)
utilspy = os.path.join(sinto_dir, "utils.py")
exec(open(utilspy).read())
read_cell_barcode_file(os.path.expanduser("~/data/10x/pbmc_3k/test_atac_barcodes.txt"))
>>> read_cell_barcode_file(os.path.expanduser("~/data/10x/pbmc_3k/test_atac_barcodes.txt"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 204, in read_cell_barcode_file
IndexError: list index out of range
```

The [documentation](https://timoast.github.io/sinto/basic_usage.html#filter-cell-barcodes-from-bam-file) reads: 

```
File or comma-separated list of cell barcodes. Can be gzip compressed
```

Thank you for your help!

Best,
Marcel

**Comment by timoast** [comment]
Sorry the function documentation should be updated, the file needs to have two columns: cell barcode and group. There's an example on the sinto website

**Comment by JihedC** [comment]
Thanks for the issue, I had the same problem just now and it seems to solve it! :)
