### ISSUE TITLE
collapsing reads

### ISSUE THREAD

**Issue by rtyags** [timoast/sinto#48]
Hi Tim,

I am trying to figure out how to merge bed files resulting from multiple sinto runs (so as to be able to run it on a split bam file and parallelize it). for this, I am trying to understand how sinto collapses reads. In the user guide, you say "Within a cell barcode, collapse fragments that share a start or end coordinate on the same chromosome." Could you explain why this is done. I would've thought that for the cell barcode, one would want to collapse only those fragments that have the same start AND end positions. why do you say "start or end"?

**Comment by timoast** [comment]
In my experience, there can often be many fragments that share the same cell barcode and either start or end, but the other coordinate is off by only a few bp. These are likely due to technical error (PCR, sequencing, alignment) rather than originating from different molecules. We found adding the step of collapsing fragments within a cell that shared at least one start or end coordinate removed all of these extra fragments that were off by only a few bp.

**Comment by rtyags** [comment]
Thanks for your response Tim. Is there a threshold used for "only a few bp"? I have noticed cases where fragments from the same cell having the same start loci end up not getting filtered out, presumably because the end location isn't off by just a few bp. e.g. in one of the bed files my sinto run resulted in, I see these records:

chrM	10165	10236	ACTCACTGTTGGGTTA-1	1
chrM	10165	10257	ACTCACTGTTGGGTTA-1	1
chrM	9464	9528	ACTCACTGTTGGGTTA-1	1
chrM	9464	9602	ACTCACTGTTGGGTTA-1	1

Could you help me understand this output?

Thanks!

**Comment by rtyags** [comment]
As a follow up, looking at the code it seems to me that you use 20 as the threshold for this. i.e. if one end is the same, we allow the other end to be up to 20 bases away for it to still be considered a duplicate. Is that correct? 

However, even in that case, I'm confused because I see multiple cases where the end is the same, the start is <20 bases away, but these are still not counted separately (i.e., they are considered duplicates) by sinto. e.g. with the following 4 reads:

A00261:525:HK77VDSX3:1:1133:17969:2613	99	chrM	9947	60	150M	=	10023	226	GGTTTGACTATTTCTGTATGTCTCCATCTATTGATGAGGGTCTTACTCTTTTAGTATAAATAGTACCGTTAACTTCCAATTAACTAGTTTTGACAACATTCAAAAAAGAGTAATAAACTTCGCCTTAATTTTAATAATCAACACCCTCCT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFF::FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	MD:Z:150	AS:i:150	XS:i:34	CR:Z:ACAGGCTCAGGAGGGT	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:AAAGCAAGTGGAAACG-1	BC:Z:TCGAATTG	QT:Z:FFFFFFFF	RG:Z:Sample_output:MissingLibrary:1:HK77VDSX3:1
A00261:525:HK77VDSX3:1:1133:17969:2613	147	chrM	10023	60	150M	=	9947	-226	CAATTAACTAGTTTTGACAACATTCAAAAAAGAGTAATAAACTTCGCCTTAATTTTAATAATCAACACCCTCCTAGCCTTACTACTAATAATTATTACATTTTGACTACCACAACTCAACGGCTACATAGAAAAATCCACCCCTTACGAG	:FFFFFFFFFFFFFFFF:FFFFFF:FFFF:FFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	MD:Z:150	AS:i:150	XS:i:0	CR:Z:ACAGGCTCAGGAGGGT	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:AAAGCAAGTGGAAACG-1	BC:Z:TCGAATTG	QT:Z:FFFFFFFF	RG:Z:Sample_output:MissingLibrary:1:HK77VDSX3:1
A00261:525:HK77VDSX3:1:1370:20518:3302	99	chrM	10092	60	81M	=	10092	81	CTCCTAGCCTTACTACTAATAATTATTACATTTTGACTACCACAACTCAACGGCTACATAGAAAAATCCACCCCTTACGAG	FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	MD:Z:81	AS:i:81	XS:i:0	CR:Z:ACAGGCTCAGGAGGGT	CY:Z:FFFFFF,FFFFFFFFF	CB:Z:AAAGCAAGTGGAAACG-1	BC:Z:CGAGTGAT	QT:Z:FFFFFFFF	RG:Z:Sample_output:MissingLibrary:1:HK77VDSX3:1	TR:Z:CTGTCTCTTATACACATCTCCGAGCCCACGAGACCGAGTGATATCTCGTATGCCGTCTTCTGCTTGAAA	TQ:Z:FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFF
A00261:525:HK77VDSX3:1:1370:20518:3302	147	chrM	10092	60	81M	=	10092	-81	CTCCTAGCCTTACTACTAATAATTATTACATTTTGACTACCACAACTCAACGGCTACATAGAAAAATCCACCCCTTACGAG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:0	MD:Z:81	AS:i:81	XS:i:0	CR:Z:ACAGGCTCAGGAGGGT	CY:Z:FFFFFF,FFFFFFFFF	CB:Z:AAAGCAAGTGGAAACG-1	BC:Z:CGAGTGAT	QT:Z:FFFFFFFF	RG:Z:Sample_output:MissingLibrary:1:HK77VDSX3:1	TR:Z:CTGTCTCTTATACACATCTGACGCTGCCGACGACAGACGCGACCCTCCTGAGCCTGTGTGTAGATCTCG	TQ:Z:::FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

I would have expected the following two start,end pairs to be considered separate fragments:
9950 10167
10095  10167

but sinto actually only counts the second fragment here (i.e. 10095   10167), and ignores the first. What am I missing? 

Thanks
