### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by nitinnarwade** [timoast/sinto#49]
Hi,

Thank you for developing this tool.

I am applying this code on a real-time CellRanger output where the bam file size is 35GB and I am getting this error `Failed to open file "sam_files/T10/AGGTCATTCCTAAGTG-1_7G1BJ1" : Too many open files`.

Do you have any fix for this?

Regards,
Nitin N.

**Comment by timoast** [comment]
What code are you running?

**Comment by nitinnarwade** [comment]
Thank you so much for your prompt reply.

And, sorry for the lack of details in my question.

Well, I am using `filterbarcodes.py` and my aim is to split the CellRanger bam file with `cellbarcodes`  and not with the `clusters/celltypes`

A chunk of my `cells` file is as follows:

```
AAACCCAAGTTCGCAT-1	AAACCCAAGTTCGCAT-1
AAACCCACACAAGTGG-1	AAACCCACACAAGTGG-1
AAACCCACACCTGTCT-1	AAACCCACACCTGTCT-1
AAACCCACACGCAGTC-1	AAACCCACACGCAGTC-1
AAACCCATCGGACTGC-1	AAACCCATCGGACTGC-1
AAACGAAAGGTAAAGG-1	AAACGAAAGGTAAAGG-1
AAACGAACACACCGCA-1	AAACGAACACACCGCA-1
AAACGAAGTAGAGACC-1	AAACGAAGTAGAGACC-1
AAACGAATCCAATGCA-1	AAACGAATCCAATGCA-1
AAACGAATCGGTAGGA-1	AAACGAATCGGTAGGA-1
```

I intentionally add cell barcodes in the second column to obtain actual barcode level splitting.

Thanks and Regards,
Nitin N.

**Comment by timoast** [comment]
There's a limit to the number of open files you can have at once (not related to Python / sinto). If you want to create a separate file for each cell, you're likely hitting this limit. I'd suggest splitting 1000 cells at a time to avoid this issue (split the `cells` file by every 1000 lines and run `sinto filterbarcodes` on each chunked `cells` file)

**Comment by nitinnarwade** [comment]
Yep, it worked!!

It did not occur to my mind. 
Thanks for the trick. 

Regards,
Nitin N.
