### ISSUE TITLE
Normalizing the signal - creating a bigwig

### ISSUE THREAD

**Issue by gouthamatla** [timoast/sinto#5]
Hi,

This is a very useful tool. 

I am wondering what would be the best way to nomalize the data to visualize on UCSC genome browser. I saw that CoveragePlot in Signac considers total number of reads per clusters and the total number of cells per cluster. I would like to know whats the best way to get the scaling factor which then can be used to normalize the bedGraph file. 

`genomeCoverageBed -ibam cluster_bam.bam -bg | awk -v OFS="\t" '{ $4=$4*scaling_factor; print}' > cluster_bam.bg`

Then use '`bedGraphToBigWig`' to make a bigWig.

**Comment by timoast** [comment]
I suggest using [deepTools bamCoverage](https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html) and using the RPKM normalization option. You won't be able to recreate exactly the tracks that Signac produces just by using coverage from the bam file, but it should look similar.

**Comment by gouthamatla** [comment]
Thanks for the quick reply.
