### ISSUE TITLE
Error "No space left on device"

### ISSUE THREAD

**Issue by NGroen** [timoast/sinto#57]
Dear Tim,
Thanks for developing this tool! 
I am using Sinto to create fragment files from bam files. This works successfully for the majority of the bam files, however, for the larger ones (seems >13GB) this gives the error below. 
I have limited space in my home directory, but changing the home directory to a location with plenty of diskspace did not help unfortunately. 
Would you have any advice on how to solve this problem? 
Thanks! 

```
Traceback (most recent call last):
  File "xx/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "xx/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/xy/fragments.py", line 237, in getFragments
    writeFragments(fragments=collapsed, filepath=outname)
  File "xy/fragments.py", line 28, in writeFragments
    outf.write(outstr + "\n")
OSError: [Errno 28] No space left on device
```

**Comment by timoast** [comment]
This looks like a disk space issue, I don't think there's much we can do in the code to solve it
