### ISSUE TITLE
Fuzzy barcode processing

### ISSUE THREAD

**Issue by dawe** [timoast/sinto#60]
Hi, I'm trying to incorporate `sinto` into my default processing. I've noticed that every barcode-related action works by exact matching of barcode string and there's no barcode correction step. This drops every barcode that is, say, 1-nt afar from the whitelist. What would be the preferred way to go when there's no finite barcode definition (i.e. bc can be every combination of ACGT)? I thought I can correct the fastq file containing cell barcodes before any further processing, but I'd rather not create a pseudo-duplicated file.

**Comment by timoast** [comment]
I would recommend correcting the barcodes first using something like UMITools: https://umi-tools.readthedocs.io/en/latest/

**Comment by dawe** [comment]
Excellent. In case I created a PR for this. It's pretty dumb but in principle saves the need to have an additional (possibly huge) fastq file.

**Comment by timoast** [comment]
Thanks, I think that's a good addition.

Just want to add that splitcode also has a function to extract barcode sequences, but currently no barcode correction: https://splitcode.readthedocs.io/en/latest/user_guide_extraction.html

**Comment by dawe** [comment]
I didn't know the splitcode project, my bad. 
Now adding it to the pile :-)
