### ISSUE TITLE
Sinto Fragments Output Empty

### ISSUE THREAD

**Issue by Tripfantasy** [timoast/sinto#62]
Hello, thank you for this tool! I am attempting to generate a fragments file from my indexed and sorted bam file. I have looked at a few of the closed issues and could not find a solution to my issue. (though I may be misinterpreting) I have checked if the bam file is paired end via the header which shows:

```
@CO     10x_bam_to_fastq:R1(CR:CY,UR:UY)
@CO     10x_bam_to_fastq:R2(SEQ:QUAL)
```

I'm assuming that because there is R1 and R2, that this is paired-end data. I've also checked whether the cell barcodes are included in the data. Below is an example of the records, showing a CB tag. So I've ran with the default parameters for barcode etc. 

```
VH00629:112:AAAYVHJHV:2:2105:22492:41950        16      chr1    3274476 255     90M     *       0       0       GCCAGAACTGGGACCTAAAGAATGGCAGAGAGATGCTAAGAGAAACGCTGCTGCTGTGGAGCTCCACAGGAAAGGATCTTCGTATCAGAC      CCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC      NH:i:1  HI:i:1 AS:i:88  nM:i:0  RG:Z:P3_Fzd1KO_stim:0:1:AAAYVHJHV:2     TX:Z:ENSMUSG00000051951,+       GX:Z:ENSMUSG00000051951 GN:Z:Xkr4       fx:Z:ENSMUSG00000051951 RE:A:N  xf:i:25 CR:Z:GGGTCACAGATGCTGG   CY:Z:CCCCCCCCCCCCCCCC   CB:Z:GGGTCACAGATGCTGG-1 UR:Z:CGACTTTATAAA       UY:Z:CCCCCCCCCCCC       UB:Z:CGACTTTATAAA
```

Despite this, I cannot seem to generate any fragments in my output, even if the function runs for approx 10 minutes. Any help as to what could be going wrong would be greatly appreciated! 

Here's an example of the command I'm running:

`sinto fragments -b input_sorted.bam -f test.bed -p 8`

Thank you for your time.

**Comment by timoast** [comment]
Can you show the error message that you see?

**Comment by Tripfantasy** [comment]
Hello,

I don't get any error message. It carries out the command to completion, but produces an empty file with no fragments.

**Comment by timoast** [comment]
Ok, this actually looks like a gene expression bam file, not ATAC. You won't be able to create a fragment file using a gene expression BAM file

**Comment by Tripfantasy** [comment]
Oh man, thanks for calling that out. I assumed I was given ATAC data. Sorry for the false flag!
