### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by GuiSeSanz** [timoast/sinto#63]
Hello, I wanted to use the package to filter a bam file by cellBarcode. I installed the package via pip, as in the intructions, bu I encounter the following error...

`/Library/Developer/CommandLineTools/usr/bin/python3: No module named sinto.__main__; 'sinto' is a package and cannot be directly executed`

**Comment by timoast** [comment]
what is the command you are running?

**Comment by timoast** [comment]
Ok, sinto cannot be run using `python -m sinto` you would need to use the `sinto` command on the command line. It looks like this could be a path issue, you should make sure you have the python paths set up correctly

**Comment by GuiSeSanz** [comment]
Ok, I'm trying to solve it...
When I explore the path where all the python libraries are installed, I'm able to locate sinto, in
`XXX/local/python3.11.0_gnu12.2.0_libs/lib/python3.11/site-packages/sinto`
This folder contains several scripts (see below), but I cannot see a main script or anything, Is there a way to launch it from here?
`addbarcodes.py  addtags.py  arguments.py  blocks.py  cli.py  constants.py  filterbarcodes.py  fragments.py  __init__.py  __pycache__  tagtoname.py  tagtorg.py  tagtotag.py  utils.py`

**Comment by timoast** [comment]
My guess is that you need to update your path with the path to the python installation directory. For you it could be something like `XXX/local/python3.11.0_gnu12.2.0_libs/lib/python3.11/bin/sinto`, but I'm not sure

FYI, we use python entry points to run the main function in `arguments.py` by calling `sinto` on the command line https://github.com/timoast/sinto/blob/master/setup.cfg#L27-L29. Calling individual scripts within the package like `cli.py` won't help..

**Comment by GuiSeSanz** [comment]
Ok! Thank you very much for your help! since the issue is no longer related with the library, I'll close the issue!
Thanks again!
