### ISSUE TITLE
SInto pipeline

### ISSUE THREAD

**Issue by hesbornomwandho** [timoast/sinto#64]
Hello, is it possible to run sinto Pipeline n R?

i have an .rds file with several clusters, however i am interested in pulling/generating a specific clusters(.bam files) and use ROSE algorithm(python ROSE_main.py -g HG37 -i enhancers.gff -r BAM -o Hezz -s 12500 -t 2500) to call enhancers.
how to do i go about this??
I want to generate a .bam file for each cluster of my atac-seq data for my downstream analysis..

**Comment by timoast** [comment]
Please see the docs here: https://timoast.github.io/sinto/basic_usage.html#filter-cell-barcodes-from-bam-file
