### ISSUE TITLE
filterbarcodes cell file format

### ISSUE THREAD

**Issue by cathalgking** [timoast/sinto#69]
@timoast 
The docs say that the input 'cells' file should be a 2 column file with the barcodes in the first column and the groups that the cells belong to in the second column. However, I do not have group assignments for my usage so I do not need the 2nd column for this file. Is there any way to only have 1 column as all thats needed for this cells file? 
My current work-around is to duplicate the first column (example below) but ideally I dont want to do that.
<img width="477" alt="Screenshot 2024-06-17 at 2 56 22 PM" src="https://github.com/timoast/sinto/assets/32261323/6bbc2a52-8c19-45c7-a1c1-430b01242f22">

**Comment by timoast** [comment]
If you want to create a separate file for each cell then you just need to copy the cell barcode into both columns as you've done here. There's no way to provide only one column, the format is `cell group`
