### ISSUE TITLE
filterbarcodes empty BAM file

### ISSUE THREAD

**Issue by Brawni** [timoast/sinto#9]
Hi Tim! Great idea this tool..really useful! I want to subset by barcodes a BAM file from 10x 3' scRNA  which have been already subset with samtools for a specific gene locus. sinto barcodes seems to run smoothly with no errors but then my new BAM file is empty:

` sinto filterbarcodes -b BAM_ACE2/1B1_ACE2.bam \
 -c BC_groups/1B1_ACE2.txt -o BAM_ACE2_BC/1B1_ACE2_BC.bam \
--barcodetag "CB"

Function run_filterbarcodes called with the following arguments:

bam	BAM_ACE2/1B1_ACE2.bam
cells	BC_groups/1B1_ACE2.txt
output	BAM_ACE2_BC/1B1_ACE2_BC.bam
trim_suffix	False
sam	False
nproc	1
barcode_regex	None
barcodetag	CB
func	<function run_filterbarcodes at 0x7fb2498cb8c8>

Function completed in  0.0 m 0.12 s

`
My barcodes file is a tab-delimited txt file with no quotes generated in R like this:
AGCATACTCAATCACG-1      Goblet
AGTCTTTTCATCGCTC-1      Basal
AGTGAGGTCCACGAAT-1      Basal
ATTCTACAGATTACCC-1      Secretory
CAAGGCCAGATCCCAT-1      Ciliated
CATCAGAAGGCTAGAC-1      Goblet
CATTATCCACCTCGGA-1      Secretory
CATTCGCAGCTAGCCC-1      Basal
CCACGGACACAGATTC-1      Secretory
CCTACACAGACGCACA-1      Basal
AAGGTTCCATACTACG-1      Basal
AAGTCTGCATACTCTT-1      Goblet
CGTCCATTCAAGGTAA-1      Ciliated
GATCAGTGTTCACGGC-1      Basal
GATGAAACATTCGACA-1      Ionocytes
GGACATTAGGTCATCT-1      Basal
GGGTTGCCACGACGAA-1      Secretory
ACGATACCACAGAGGT-1      Basal
TCATTACTCGCCGTGA-1      Goblet
TGAGCATTCTGCTGTC-1      Basal
ACGGCCACAGCGATCC-1      Goblet
TTGACTTCAGACTCGC-1      Basal
TTTGCGCCATGAACCT-1      Ciliated
ACTTTCACACTGTTAG-1      Goblet

I checked whether barcodes are actually found in the bam file and that seem to be the case at least for the couple i tested:

`samtools view BAM_ACE2/1B1_ACE2.bam | grep -i "AGCATACTCAATCACG-1"
A00198:47:H5L7HDMXX:2:1442:24578:30373	256	X	15601544	0	37M2087N53M	*	GGCGCGATCTCGGCTCACTGCAAGCTCTGCCTCCCGGGTTCACGCCATTCTCCTGCCTCGGCCTCCCGAGTAGCTGGGACTACAGGCGCC	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:7	HI:i:7	AS:i:85	nM:i:1	RE:A:I	BC:Z:CCTGTGCG	QT:Z:FFFFFFFF	CR:Z:AGCATACTCAATCACG	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:AGCATACTCAATCACG-1	UR:Z:CCACTTAGTT	UY:Z:FFFFFFFFFF	UB:Z:CCACTTAGTT	RG:Z:1B1:MissingLibrary:1:H5L7HDMXX:2
`
Also I should i get a bam file for each cell group according to documentation but my output is only one empty BAM file

Much appreciated

**Comment by timoast** [comment]
Hi @Brawni, sorry for the delay here. Can you tell me which version you're using? Also, are you 100% sure that the file is tab-delimited? Can you post the R code you used to write the file?

**Comment by timoast** [comment]
Can you update to the latest version and see if that works? The option to split into multiple files was only added in [0.4](https://timoast.github.io/sinto/#id5), in 0.3.3 you needed to specify separate lists of cell barcodes for each group of cells you wanted to create a separate bam for

**Comment by Brawni** [comment]
Updated to v 0.5.0. Now when i run it i get the following error:
```
 sinto filterbarcodes -b BAM_ACE2/1B1_ACE2.bam \
 -c BC_groups/1B1_ACE2.txt -o BAM_ACE2_BC/1B1_ACE2_BC.bam \
--barcodetag "CB"
usage: sinto [-h] [-v] {filterbarcodes,addtags,tagtorg,fragments} ...
sinto: error: unrecognized arguments: -o BAM_ACE2_BC/1B1_ACE2_BC.bam
```

**Comment by timoast** [comment]
The `-o` parameter was removed when the ability to split into many different groups was added, the output files are now named according to the group name (ie, for your file you'll get Basal.bam, Secretory.bam, etc)

**Comment by Brawni** [comment]
Ah yes, great it works! 
It would be good to being able to specify output folder.

Thanks for your help!

**Comment by timoast** [comment]
Yeah that's a good idea, I can try to add an output path prefix option soon
